--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/GiantQuartz/NpcDialog
build-by-default: true
branches:
  - master
projects:
  NpcDialog:
    path: ""
    model: virion
    type: library
...
